name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml

      - name: Install package
        run: |
          pip install .[tests]

      - name: Test
        if: matrix.python-version != '3.12'
        run: |
          pytest

      - name: Test with coverage
        if: matrix.python-version == '3.12'
        run: |
          pytest --cov simdec --cov-report term-missing
